### ISSUE TITLE
Installing on Umbraco 10 - View not found

### ISSUE THREAD

**Issue by NikRimington** [nathanwoulfe/Blip#1]
Hey Nathan,

I've added this package to a v10 site (I know it says it supports 8 and 9 but no mention of 10). It appears to install with no problem, however when it comes to configuring the editor the following error occurs:

![image](https://user-images.githubusercontent.com/13313745/214269096-487ebeda-c438-40f5-a4ba-de2b669da731.png)

This error occurs when loading the config screen and again after picking a source node:
![image](https://user-images.githubusercontent.com/13313745/214269518-add01234-b5db-4238-8cd9-2892fa4fd730.png)

I'm not sure why this isn't available as the file exists in the nuget package:

![image](https://user-images.githubusercontent.com/13313745/214270718-36648cb2-1c9d-43bc-b04a-b0a247c8d5f1.png)

![image](https://user-images.githubusercontent.com/13313745/214270699-c4bce538-86f6-4882-a629-201f8459ddbb.png)

**Comment by nathanwoulfe** [comment]
Heya @NikRimington that's a bit odd... Plan for 10/11 release will include RCL, which will hopefully tidy this up. No (obvious) reason for it to not work on 10/11, given it's all client side

**Comment by NikRimington** [comment]
It's very odd. Is there anything that I/we can do to help get this working properly for the v10/v11 release? :-)

**Comment by nathanwoulfe** [comment]
Hey @NikRimington have a crack now with the fresh v10 version - I had the same issue running the previous version on Umbraco 10 and 11, not sure why it was failing but should be working nicely with the new v10/v11 versions
