### ISSUE TITLE
Is Umbraco 13 support possible?

### ISSUE THREAD

**Issue by jeroenmink2** [nathanwoulfe/Blip#3]
We have several sites using Blip running Umbraco 12, but want to upgrade to Umbraco 13 to get on LTS, can the package be supported for V13?

**Comment by nathanwoulfe** [comment]
Hey @jeroenmink2 I'll have a look at this sometime this week - shouldn't be a big deal to get it working for 13

**Comment by nathanwoulfe** [comment]
@jeroenmink2 I'm a bit slow on the replies, but 13 is out.
